[2024-02-19T18:27:39.237+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dag_with_postgres_operator_v06.create_postgres_table scheduled__2024-02-18T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
