[2024-02-16T16:39:16.596+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_backup_v3.task1 manual__2024-02-16T16:39:14.783665+00:00 [queued]>
[2024-02-16T16:39:16.609+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_backup_v3.task1 manual__2024-02-16T16:39:14.783665+00:00 [queued]>
[2024-02-16T16:39:16.609+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-16T16:39:16.630+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): task1> on 2024-02-16 16:39:14.783665+00:00
[2024-02-16T16:39:16.640+0000] {standard_task_runner.py:60} INFO - Started process 229 to run task
[2024-02-16T16:39:16.649+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backup_v3', 'task1', 'manual__2024-02-16T16:39:14.783665+00:00', '--job-id', '399', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_backfill.py', '--cfg-path', '/tmp/tmp5a2d9h4u']
[2024-02-16T16:39:16.650+0000] {standard_task_runner.py:88} INFO - Job 399: Subtask task1
[2024-02-16T16:39:16.714+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_catchup_backup_v3.task1 manual__2024-02-16T16:39:14.783665+00:00 [running]> on host 7c2825a65d38
[2024-02-16T16:39:16.825+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Shiv' AIRFLOW_CTX_DAG_ID='dag_with_catchup_backup_v3' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-02-16T16:39:14.783665+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-16T16:39:14.783665+00:00'
[2024-02-16T16:39:16.826+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-16T16:39:16.827+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Yellow, this is bash command being bashing around']
[2024-02-16T16:39:16.842+0000] {subprocess.py:86} INFO - Output:
[2024-02-16T16:39:16.845+0000] {subprocess.py:93} INFO - Yellow, this is bash command being bashing around
[2024-02-16T16:39:16.846+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-16T16:39:16.896+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_backup_v3, task_id=task1, execution_date=20240216T163914, start_date=20240216T163916, end_date=20240216T163916
[2024-02-16T16:39:16.943+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-16T16:39:16.967+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
