[2024-02-27T04:16:25.664+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v01.get_matplotlib scheduled__2024-02-23T00:00:00+00:00 [queued]>
[2024-02-27T04:16:25.988+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v01.get_matplotlib scheduled__2024-02-23T00:00:00+00:00 [queued]>
[2024-02-27T04:16:25.989+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-27T04:16:26.079+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_matplotlib> on 2024-02-23 00:00:00+00:00
[2024-02-27T04:16:26.207+0000] {standard_task_runner.py:60} INFO - Started process 149 to run task
[2024-02-27T04:16:26.407+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v01', 'get_matplotlib', 'scheduled__2024-02-23T00:00:00+00:00', '--job-id', '498', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmp2jz43kns']
[2024-02-27T04:16:26.409+0000] {standard_task_runner.py:88} INFO - Job 498: Subtask get_matplotlib
[2024-02-27T04:16:27.070+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_python_dependencies_v01.get_matplotlib scheduled__2024-02-23T00:00:00+00:00 [running]> on host f592a0b4b395
[2024-02-27T04:16:28.449+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Shiv' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v01' AIRFLOW_CTX_TASK_ID='get_matplotlib' AIRFLOW_CTX_EXECUTION_DATE='2024-02-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-23T00:00:00+00:00'
[2024-02-27T04:16:28.453+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 18, in get_matplotlib
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-02-27T04:16:28.557+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v01, task_id=get_matplotlib, execution_date=20240223T000000, start_date=20240227T041625, end_date=20240227T041628
[2024-02-27T04:16:28.686+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 498 for task get_matplotlib (No module named 'matplotlib'; 149)
[2024-02-27T04:16:28.933+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-27T04:16:29.201+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
