[2024-02-27T04:16:28.948+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v01.get_matplotlib scheduled__2024-02-26T00:00:00+00:00 [queued]>
[2024-02-27T04:16:29.005+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v01.get_matplotlib scheduled__2024-02-26T00:00:00+00:00 [queued]>
[2024-02-27T04:16:29.008+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-27T04:16:29.439+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_matplotlib> on 2024-02-26 00:00:00+00:00
[2024-02-27T04:16:29.688+0000] {standard_task_runner.py:60} INFO - Started process 154 to run task
[2024-02-27T04:16:29.753+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v01', 'get_matplotlib', 'scheduled__2024-02-26T00:00:00+00:00', '--job-id', '505', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpdhkav6km']
[2024-02-27T04:16:29.809+0000] {standard_task_runner.py:88} INFO - Job 505: Subtask get_matplotlib
[2024-02-27T04:16:31.344+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_python_dependencies_v01.get_matplotlib scheduled__2024-02-26T00:00:00+00:00 [running]> on host f592a0b4b395
[2024-02-27T04:16:32.234+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Shiv' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v01' AIRFLOW_CTX_TASK_ID='get_matplotlib' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-26T00:00:00+00:00'
[2024-02-27T04:16:32.236+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 18, in get_matplotlib
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-02-27T04:16:32.284+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v01, task_id=get_matplotlib, execution_date=20240226T000000, start_date=20240227T041628, end_date=20240227T041632
[2024-02-27T04:16:32.359+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 505 for task get_matplotlib (No module named 'matplotlib'; 154)
[2024-02-27T04:16:32.463+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-27T04:16:32.555+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
