[2024-02-19T16:39:52.576+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_backup_v3.task1 scheduled__2024-02-18T00:00:00+00:00 [queued]>
[2024-02-19T16:39:52.585+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_backup_v3.task1 scheduled__2024-02-18T00:00:00+00:00 [queued]>
[2024-02-19T16:39:52.586+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-19T16:39:52.608+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): task1> on 2024-02-18 00:00:00+00:00
[2024-02-19T16:39:52.615+0000] {standard_task_runner.py:60} INFO - Started process 54 to run task
[2024-02-19T16:39:52.621+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backup_v3', 'task1', 'scheduled__2024-02-18T00:00:00+00:00', '--job-id', '415', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_backfill.py', '--cfg-path', '/tmp/tmpd0y9vx54']
[2024-02-19T16:39:52.622+0000] {standard_task_runner.py:88} INFO - Job 415: Subtask task1
[2024-02-19T16:39:52.700+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_catchup_backup_v3.task1 scheduled__2024-02-18T00:00:00+00:00 [running]> on host 7c2825a65d38
[2024-02-19T16:39:52.891+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Shiv' AIRFLOW_CTX_DAG_ID='dag_with_catchup_backup_v3' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-18T00:00:00+00:00'
[2024-02-19T16:39:52.894+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-19T16:39:52.896+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Yellow, this is bash command being bashing around']
[2024-02-19T16:39:52.921+0000] {subprocess.py:86} INFO - Output:
[2024-02-19T16:39:52.923+0000] {subprocess.py:93} INFO - Yellow, this is bash command being bashing around
[2024-02-19T16:39:52.924+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-19T16:39:52.980+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_backup_v3, task_id=task1, execution_date=20240218T000000, start_date=20240219T163952, end_date=20240219T163952
[2024-02-19T16:39:53.013+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-19T16:39:53.050+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
