[2024-02-16T16:47:03.898+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_backup_v3.task1 backfill__2024-02-02T00:00:00+00:00 [queued]>
[2024-02-16T16:47:03.982+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_backup_v3.task1 backfill__2024-02-02T00:00:00+00:00 [queued]>
[2024-02-16T16:47:03.988+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-16T16:47:04.113+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): task1> on 2024-02-02 00:00:00+00:00
[2024-02-16T16:47:04.168+0000] {standard_task_runner.py:60} INFO - Started process 366 to run task
[2024-02-16T16:47:04.189+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backup_v3', 'task1', 'backfill__2024-02-02T00:00:00+00:00', '--job-id', '406', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_backfill.py', '--cfg-path', '/tmp/tmpv0vuzz83']
[2024-02-16T16:47:04.231+0000] {standard_task_runner.py:88} INFO - Job 406: Subtask task1
[2024-02-16T16:47:04.461+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_catchup_backup_v3.task1 backfill__2024-02-02T00:00:00+00:00 [running]> on host 7c2825a65d38
[2024-02-16T16:47:04.998+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Shiv' AIRFLOW_CTX_DAG_ID='dag_with_catchup_backup_v3' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-02-02T00:00:00+00:00'
[2024-02-16T16:47:04.999+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-16T16:47:05.014+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Yellow, this is bash command being bashing around']
[2024-02-16T16:47:05.175+0000] {subprocess.py:86} INFO - Output:
[2024-02-16T16:47:05.190+0000] {subprocess.py:93} INFO - Yellow, this is bash command being bashing around
[2024-02-16T16:47:05.199+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-16T16:47:05.267+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_backup_v3, task_id=task1, execution_date=20240202T000000, start_date=20240216T164703, end_date=20240216T164705
[2024-02-16T16:47:05.410+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-16T16:47:05.456+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
